package com.j3a.assurance.model;

// Generated 5 mai 2015 11:21:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Etatc10tabbExercice generated by hbm2java
 */
@Entity
@Table(name = "etatc10tabb_exercice", catalog = "zeusbd")
public class Etatc10tabbExercice implements java.io.Serializable {

	private Etatc10tabbExerciceId id;
	private Etatc10TabB etatc10TabB;
	private Exercice exercice;
	private BigDecimal reglement;
	private BigDecimal provisions;
	private BigDecimal totalbrutsinistre;
	private BigDecimal recoursencaisse;
	private BigDecimal recoursaencaisse;
	private BigDecimal totalrecours;
	private BigDecimal totalnetsinistre;
	private BigDecimal primeacquise;
	private BigDecimal rapportsinistreprimes;
	private String libelleexo;
	private BigDecimal regelement;
	private Character verif;

	public Etatc10tabbExercice() {
	}

	public Etatc10tabbExercice(Etatc10tabbExerciceId id,
			Etatc10TabB etatc10TabB, Exercice exercice) {
		this.id = id;
		this.etatc10TabB = etatc10TabB;
		this.exercice = exercice;
	}

	public Etatc10tabbExercice(Etatc10tabbExerciceId id,
			Etatc10TabB etatc10TabB, Exercice exercice, BigDecimal reglement,
			BigDecimal provisions, BigDecimal totalbrutsinistre,
			BigDecimal recoursencaisse, BigDecimal recoursaencaisse,
			BigDecimal totalrecours, BigDecimal totalnetsinistre,
			BigDecimal primeacquise, BigDecimal rapportsinistreprimes,
			String libelleexo, BigDecimal regelement, Character verif) {
		this.id = id;
		this.etatc10TabB = etatc10TabB;
		this.exercice = exercice;
		this.reglement = reglement;
		this.provisions = provisions;
		this.totalbrutsinistre = totalbrutsinistre;
		this.recoursencaisse = recoursencaisse;
		this.recoursaencaisse = recoursaencaisse;
		this.totalrecours = totalrecours;
		this.totalnetsinistre = totalnetsinistre;
		this.primeacquise = primeacquise;
		this.rapportsinistreprimes = rapportsinistreprimes;
		this.libelleexo = libelleexo;
		this.regelement = regelement;
		this.verif = verif;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeexercice", column = @Column(name = "CODEEXERCICE", nullable = false)),
			@AttributeOverride(name = "codeetatc10b", column = @Column(name = "CODEETATC10B", nullable = false)) })
	public Etatc10tabbExerciceId getId() {
		return this.id;
	}

	public void setId(Etatc10tabbExerciceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEETATC10B", nullable = false, insertable = false, updatable = false)
	public Etatc10TabB getEtatc10TabB() {
		return this.etatc10TabB;
	}

	public void setEtatc10TabB(Etatc10TabB etatc10TabB) {
		this.etatc10TabB = etatc10TabB;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEEXERCICE", nullable = false, insertable = false, updatable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@Column(name = "REGLEMENT")
	public BigDecimal getReglement() {
		return this.reglement;
	}

	public void setReglement(BigDecimal reglement) {
		this.reglement = reglement;
	}

	@Column(name = "PROVISIONS")
	public BigDecimal getProvisions() {
		return this.provisions;
	}

	public void setProvisions(BigDecimal provisions) {
		this.provisions = provisions;
	}

	@Column(name = "TOTALBRUTSINISTRE")
	public BigDecimal getTotalbrutsinistre() {
		return this.totalbrutsinistre;
	}

	public void setTotalbrutsinistre(BigDecimal totalbrutsinistre) {
		this.totalbrutsinistre = totalbrutsinistre;
	}

	@Column(name = "RECOURSENCAISSE")
	public BigDecimal getRecoursencaisse() {
		return this.recoursencaisse;
	}

	public void setRecoursencaisse(BigDecimal recoursencaisse) {
		this.recoursencaisse = recoursencaisse;
	}

	@Column(name = "RECOURSAENCAISSE")
	public BigDecimal getRecoursaencaisse() {
		return this.recoursaencaisse;
	}

	public void setRecoursaencaisse(BigDecimal recoursaencaisse) {
		this.recoursaencaisse = recoursaencaisse;
	}

	@Column(name = "TOTALRECOURS")
	public BigDecimal getTotalrecours() {
		return this.totalrecours;
	}

	public void setTotalrecours(BigDecimal totalrecours) {
		this.totalrecours = totalrecours;
	}

	@Column(name = "TOTALNETSINISTRE")
	public BigDecimal getTotalnetsinistre() {
		return this.totalnetsinistre;
	}

	public void setTotalnetsinistre(BigDecimal totalnetsinistre) {
		this.totalnetsinistre = totalnetsinistre;
	}

	@Column(name = "PRIMEACQUISE")
	public BigDecimal getPrimeacquise() {
		return this.primeacquise;
	}

	public void setPrimeacquise(BigDecimal primeacquise) {
		this.primeacquise = primeacquise;
	}

	@Column(name = "RAPPORTSINISTREPRIMES")
	public BigDecimal getRapportsinistreprimes() {
		return this.rapportsinistreprimes;
	}

	public void setRapportsinistreprimes(BigDecimal rapportsinistreprimes) {
		this.rapportsinistreprimes = rapportsinistreprimes;
	}

	@Column(name = "LIBELLEEXO", length = 10)
	public String getLibelleexo() {
		return this.libelleexo;
	}

	public void setLibelleexo(String libelleexo) {
		this.libelleexo = libelleexo;
	}

	@Column(name = "REGELEMENT")
	public BigDecimal getRegelement() {
		return this.regelement;
	}

	public void setRegelement(BigDecimal regelement) {
		this.regelement = regelement;
	}

	@Column(name = "VERIF", length = 1)
	public Character getVerif() {
		return this.verif;
	}

	public void setVerif(Character verif) {
		this.verif = verif;
	}

}
