package com.j3a.assurance.model;

// Generated 5 mai 2015 11:21:10 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtatCima generated by hbm2java
 */
@Entity
@Table(name = "etat_cima", catalog = "zeusbd")
public class EtatCima implements java.io.Serializable {

	private String codeEtatCima;
	private Etatc10TabA etatc10TabA;
	private Short exerciceConcerne;
	private String societeCima;
	private String paysCima;
	private Date dateEtat;
	private Set<EntrepriseCaution> entrepriseCautions = new HashSet<EntrepriseCaution>(
			0);
	private Set<PaysAction> paysActions = new HashSet<PaysAction>(0);
	private Set<Etatc10b> etatc10bs = new HashSet<Etatc10b>(0);
	private Set<Feuillebilan> feuillebilans = new HashSet<Feuillebilan>(0);
	private Set<ObligationEmprunt> obligationEmprunts = new HashSet<ObligationEmprunt>(
			0);
	private Set<Branche> branches = new HashSet<Branche>(0);
	private Set<Portefeuilles> portefeuilleses = new HashSet<Portefeuilles>(0);
	private Set<Ria> rias = new HashSet<Ria>(0);
	private Set<Accords> accordses = new HashSet<Accords>(0);
	private Set<Direction> directions = new HashSet<Direction>(0);
	private Set<PersonneCaution> personneCautions = new HashSet<PersonneCaution>(
			0);
	private Set<EffectifPersonnel> effectifPersonnels = new HashSet<EffectifPersonnel>(
			0);
	private Set<ModifiCapital> modifiCapitals = new HashSet<ModifiCapital>(0);
	private Set<CegCredit> cegCredits = new HashSet<CegCredit>(0);
	private Set<ActionnaireConseil> actionnaireConseils = new HashSet<ActionnaireConseil>(
			0);
	private Set<EtatC4> etatC4s = new HashSet<EtatC4>(0);
	private Set<EtatC5> etatC5s = new HashSet<EtatC5>(0);
	private Set<Etatc10a> etatc10as = new HashSet<Etatc10a>(0);
	private Set<Cgpp> cgpps = new HashSet<Cgpp>(0);
	private Set<Etatc9> etatc9s = new HashSet<Etatc9>(0);
	private Set<CegDebit> cegDebits = new HashSet<CegDebit>(0);
	private Set<Etatc10TabB> etatc10TabBs = new HashSet<Etatc10TabB>(0);
	private Set<Etatc1> etatc1s = new HashSet<Etatc1>(0);

	public EtatCima() {
	}

	public EtatCima(String codeEtatCima) {
		this.codeEtatCima = codeEtatCima;
	}

	public EtatCima(String codeEtatCima, Etatc10TabA etatc10TabA,
			Short exerciceConcerne, String societeCima, String paysCima,
			Date dateEtat, Set<EntrepriseCaution> entrepriseCautions,
			Set<PaysAction> paysActions, Set<Etatc10b> etatc10bs,
			Set<Feuillebilan> feuillebilans,
			Set<ObligationEmprunt> obligationEmprunts, Set<Branche> branches,
			Set<Portefeuilles> portefeuilleses, Set<Ria> rias,
			Set<Accords> accordses, Set<Direction> directions,
			Set<PersonneCaution> personneCautions,
			Set<EffectifPersonnel> effectifPersonnels,
			Set<ModifiCapital> modifiCapitals, Set<CegCredit> cegCredits,
			Set<ActionnaireConseil> actionnaireConseils, Set<EtatC4> etatC4s,
			Set<EtatC5> etatC5s, Set<Etatc10a> etatc10as, Set<Cgpp> cgpps,
			Set<Etatc9> etatc9s, Set<CegDebit> cegDebits,
			Set<Etatc10TabB> etatc10TabBs, Set<Etatc1> etatc1s) {
		this.codeEtatCima = codeEtatCima;
		this.etatc10TabA = etatc10TabA;
		this.exerciceConcerne = exerciceConcerne;
		this.societeCima = societeCima;
		this.paysCima = paysCima;
		this.dateEtat = dateEtat;
		this.entrepriseCautions = entrepriseCautions;
		this.paysActions = paysActions;
		this.etatc10bs = etatc10bs;
		this.feuillebilans = feuillebilans;
		this.obligationEmprunts = obligationEmprunts;
		this.branches = branches;
		this.portefeuilleses = portefeuilleses;
		this.rias = rias;
		this.accordses = accordses;
		this.directions = directions;
		this.personneCautions = personneCautions;
		this.effectifPersonnels = effectifPersonnels;
		this.modifiCapitals = modifiCapitals;
		this.cegCredits = cegCredits;
		this.actionnaireConseils = actionnaireConseils;
		this.etatC4s = etatC4s;
		this.etatC5s = etatC5s;
		this.etatc10as = etatc10as;
		this.cgpps = cgpps;
		this.etatc9s = etatc9s;
		this.cegDebits = cegDebits;
		this.etatc10TabBs = etatc10TabBs;
		this.etatc1s = etatc1s;
	}

	@Id
	@Column(name = "CODE_ETAT_CIMA", unique = true, nullable = false, length = 20)
	public String getCodeEtatCima() {
		return this.codeEtatCima;
	}

	public void setCodeEtatCima(String codeEtatCima) {
		this.codeEtatCima = codeEtatCima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEETATC10")
	public Etatc10TabA getEtatc10TabA() {
		return this.etatc10TabA;
	}

	public void setEtatc10TabA(Etatc10TabA etatc10TabA) {
		this.etatc10TabA = etatc10TabA;
	}

	@Column(name = "EXERCICE_CONCERNE")
	public Short getExerciceConcerne() {
		return this.exerciceConcerne;
	}

	public void setExerciceConcerne(Short exerciceConcerne) {
		this.exerciceConcerne = exerciceConcerne;
	}

	@Column(name = "SOCIETE_CIMA", length = 60)
	public String getSocieteCima() {
		return this.societeCima;
	}

	public void setSocieteCima(String societeCima) {
		this.societeCima = societeCima;
	}

	@Column(name = "PAYS_CIMA", length = 60)
	public String getPaysCima() {
		return this.paysCima;
	}

	public void setPaysCima(String paysCima) {
		this.paysCima = paysCima;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ETAT", length = 10)
	public Date getDateEtat() {
		return this.dateEtat;
	}

	public void setDateEtat(Date dateEtat) {
		this.dateEtat = dateEtat;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "entreprisecaution_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_ENTREP_CAUT", nullable = false, updatable = false) })
	public Set<EntrepriseCaution> getEntrepriseCautions() {
		return this.entrepriseCautions;
	}

	public void setEntrepriseCautions(Set<EntrepriseCaution> entrepriseCautions) {
		this.entrepriseCautions = entrepriseCautions;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "paysaction_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_PA", nullable = false, updatable = false) })
	public Set<PaysAction> getPaysActions() {
		return this.paysActions;
	}

	public void setPaysActions(Set<PaysAction> paysActions) {
		this.paysActions = paysActions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Etatc10b> getEtatc10bs() {
		return this.etatc10bs;
	}

	public void setEtatc10bs(Set<Etatc10b> etatc10bs) {
		this.etatc10bs = etatc10bs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Feuillebilan> getFeuillebilans() {
		return this.feuillebilans;
	}

	public void setFeuillebilans(Set<Feuillebilan> feuillebilans) {
		this.feuillebilans = feuillebilans;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "obligation_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_OB_EMP", nullable = false, updatable = false) })
	public Set<ObligationEmprunt> getObligationEmprunts() {
		return this.obligationEmprunts;
	}

	public void setObligationEmprunts(Set<ObligationEmprunt> obligationEmprunts) {
		this.obligationEmprunts = obligationEmprunts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "branche_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_BRANCHE", nullable = false, updatable = false) })
	public Set<Branche> getBranches() {
		return this.branches;
	}

	public void setBranches(Set<Branche> branches) {
		this.branches = branches;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "etatCimas")
	public Set<Portefeuilles> getPortefeuilleses() {
		return this.portefeuilleses;
	}

	public void setPortefeuilleses(Set<Portefeuilles> portefeuilleses) {
		this.portefeuilleses = portefeuilleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Ria> getRias() {
		return this.rias;
	}

	public void setRias(Set<Ria> rias) {
		this.rias = rias;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "accord_cima", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_ACCORD", nullable = false, updatable = false) })
	public Set<Accords> getAccordses() {
		return this.accordses;
	}

	public void setAccordses(Set<Accords> accordses) {
		this.accordses = accordses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "etatCimas")
	public Set<Direction> getDirections() {
		return this.directions;
	}

	public void setDirections(Set<Direction> directions) {
		this.directions = directions;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "personnecaut_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_PERS_CAUT", nullable = false, updatable = false) })
	public Set<PersonneCaution> getPersonneCautions() {
		return this.personneCautions;
	}

	public void setPersonneCautions(Set<PersonneCaution> personneCautions) {
		this.personneCautions = personneCautions;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "etatCimas")
	public Set<EffectifPersonnel> getEffectifPersonnels() {
		return this.effectifPersonnels;
	}

	public void setEffectifPersonnels(Set<EffectifPersonnel> effectifPersonnels) {
		this.effectifPersonnels = effectifPersonnels;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "modifcapital_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_MODIF_CAP", nullable = false, updatable = false) })
	public Set<ModifiCapital> getModifiCapitals() {
		return this.modifiCapitals;
	}

	public void setModifiCapitals(Set<ModifiCapital> modifiCapitals) {
		this.modifiCapitals = modifiCapitals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<CegCredit> getCegCredits() {
		return this.cegCredits;
	}

	public void setCegCredits(Set<CegCredit> cegCredits) {
		this.cegCredits = cegCredits;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "etatCimas")
	public Set<ActionnaireConseil> getActionnaireConseils() {
		return this.actionnaireConseils;
	}

	public void setActionnaireConseils(
			Set<ActionnaireConseil> actionnaireConseils) {
		this.actionnaireConseils = actionnaireConseils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<EtatC4> getEtatC4s() {
		return this.etatC4s;
	}

	public void setEtatC4s(Set<EtatC4> etatC4s) {
		this.etatC4s = etatC4s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<EtatC5> getEtatC5s() {
		return this.etatC5s;
	}

	public void setEtatC5s(Set<EtatC5> etatC5s) {
		this.etatC5s = etatC5s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Etatc10a> getEtatc10as() {
		return this.etatc10as;
	}

	public void setEtatc10as(Set<Etatc10a> etatc10as) {
		this.etatc10as = etatc10as;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Cgpp> getCgpps() {
		return this.cgpps;
	}

	public void setCgpps(Set<Cgpp> cgpps) {
		this.cgpps = cgpps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Etatc9> getEtatc9s() {
		return this.etatc9s;
	}

	public void setEtatc9s(Set<Etatc9> etatc9s) {
		this.etatc9s = etatc9s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<CegDebit> getCegDebits() {
		return this.cegDebits;
	}

	public void setCegDebits(Set<CegDebit> cegDebits) {
		this.cegDebits = cegDebits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Etatc10TabB> getEtatc10TabBs() {
		return this.etatc10TabBs;
	}

	public void setEtatc10TabBs(Set<Etatc10TabB> etatc10TabBs) {
		this.etatc10TabBs = etatc10TabBs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatCima")
	public Set<Etatc1> getEtatc1s() {
		return this.etatc1s;
	}

	public void setEtatc1s(Set<Etatc1> etatc1s) {
		this.etatc1s = etatc1s;
	}

}
