package com.j3a.assurance.model;

// Generated 5 mai 2015 11:21:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * ObligationEmprunt generated by hbm2java
 */
@Entity
@Table(name = "obligation_emprunt", catalog = "zeusbd")
public class ObligationEmprunt implements java.io.Serializable {

	private String codeObEmp;
	private Exercice exercice;
	private String nature;
	private BigDecimal montant;
	private String type;
	private Remboursement remboursement;
	private Amortissement amortissement;
	private Emission emission;
	private Set<EtatCima> etatCimas = new HashSet<EtatCima>(0);

	public ObligationEmprunt() {
	}

	public ObligationEmprunt(String codeObEmp, Exercice exercice) {
		this.codeObEmp = codeObEmp;
		this.exercice = exercice;
	}

	public ObligationEmprunt(String codeObEmp, Exercice exercice,
			String nature, BigDecimal montant, String type,
			Remboursement remboursement, Amortissement amortissement,
			Emission emission, Set<EtatCima> etatCimas) {
		this.codeObEmp = codeObEmp;
		this.exercice = exercice;
		this.nature = nature;
		this.montant = montant;
		this.type = type;
		this.remboursement = remboursement;
		this.amortissement = amortissement;
		this.emission = emission;
		this.etatCimas = etatCimas;
	}

	@Id
	@Column(name = "CODE_OB_EMP", unique = true, nullable = false, length = 20)
	public String getCodeObEmp() {
		return this.codeObEmp;
	}

	public void setCodeObEmp(String codeObEmp) {
		this.codeObEmp = codeObEmp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEEXERCICE", nullable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@Column(name = "NATURE", length = 30)
	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	@Column(name = "MONTANT")
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "TYPE", length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "obligationEmprunt")
	public Remboursement getRemboursement() {
		return this.remboursement;
	}

	public void setRemboursement(Remboursement remboursement) {
		this.remboursement = remboursement;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "obligationEmprunt")
	public Amortissement getAmortissement() {
		return this.amortissement;
	}

	public void setAmortissement(Amortissement amortissement) {
		this.amortissement = amortissement;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "obligationEmprunt")
	public Emission getEmission() {
		return this.emission;
	}

	public void setEmission(Emission emission) {
		this.emission = emission;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "obligationEmprunts")
	public Set<EtatCima> getEtatCimas() {
		return this.etatCimas;
	}

	public void setEtatCimas(Set<EtatCima> etatCimas) {
		this.etatCimas = etatCimas;
	}

}
