package com.j3a.assurance.model;

// Generated 5 mai 2015 11:21:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Portefeuilles generated by hbm2java
 */
@Entity
@Table(name = "portefeuilles", catalog = "zeusbd")
public class Portefeuilles implements java.io.Serializable {

	private String codePortefeilles;
	private Exercice exercice;
	private Vente vente;
	private Achat achat;
	private Set<EtatCima> etatCimas = new HashSet<EtatCima>(0);

	public Portefeuilles() {
	}

	public Portefeuilles(String codePortefeilles, Exercice exercice) {
		this.codePortefeilles = codePortefeilles;
		this.exercice = exercice;
	}

	public Portefeuilles(String codePortefeilles, Exercice exercice,
			Vente vente, Achat achat, Set<EtatCima> etatCimas) {
		this.codePortefeilles = codePortefeilles;
		this.exercice = exercice;
		this.vente = vente;
		this.achat = achat;
		this.etatCimas = etatCimas;
	}

	@Id
	@Column(name = "CODE_PORTEFEILLES", unique = true, nullable = false, length = 20)
	public String getCodePortefeilles() {
		return this.codePortefeilles;
	}

	public void setCodePortefeilles(String codePortefeilles) {
		this.codePortefeilles = codePortefeilles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEEXERCICE", nullable = false)
	public Exercice getExercice() {
		return this.exercice;
	}

	public void setExercice(Exercice exercice) {
		this.exercice = exercice;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "portefeuilles")
	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "portefeuilles")
	public Achat getAchat() {
		return this.achat;
	}

	public void setAchat(Achat achat) {
		this.achat = achat;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "poertefeil_exercice", catalog = "zeusbd", joinColumns = { @JoinColumn(name = "CODE_PORTEFEILLES", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CODE_ETAT_CIMA", nullable = false, updatable = false) })
	public Set<EtatCima> getEtatCimas() {
		return this.etatCimas;
	}

	public void setEtatCimas(Set<EtatCima> etatCimas) {
		this.etatCimas = etatCimas;
	}

}
