package com.j3a.assurance.model;

// Generated 5 mai 2015 11:21:10 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReglementApporteur generated by hbm2java
 */
@Entity
@Table(name = "reglement_apporteur", catalog = "zeusbd")
public class ReglementApporteur implements java.io.Serializable {

	private String codeReglementApp;
	private AffaireApporteur affaireApporteur;
	private CompteApporteur compteApporteur;
	private Date dateReglementApp;
	private BigDecimal montantReglementApp;
	private String typeReglement;

	public ReglementApporteur() {
	}

	public ReglementApporteur(String codeReglementApp,
			AffaireApporteur affaireApporteur) {
		this.codeReglementApp = codeReglementApp;
		this.affaireApporteur = affaireApporteur;
	}

	public ReglementApporteur(String codeReglementApp,
			AffaireApporteur affaireApporteur, CompteApporteur compteApporteur,
			Date dateReglementApp, BigDecimal montantReglementApp,
			String typeReglement) {
		this.codeReglementApp = codeReglementApp;
		this.affaireApporteur = affaireApporteur;
		this.compteApporteur = compteApporteur;
		this.dateReglementApp = dateReglementApp;
		this.montantReglementApp = montantReglementApp;
		this.typeReglement = typeReglement;
	}

	@Id
	@Column(name = "CODE_REGLEMENT_APP", unique = true, nullable = false)
	public String getCodeReglementApp() {
		return this.codeReglementApp;
	}

	public void setCodeReglementApp(String codeReglementApp) {
		this.codeReglementApp = codeReglementApp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_AFFAIRE", nullable = false)
	public AffaireApporteur getAffaireApporteur() {
		return this.affaireApporteur;
	}

	public void setAffaireApporteur(AffaireApporteur affaireApporteur) {
		this.affaireApporteur = affaireApporteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_COMPTE_APP")
	public CompteApporteur getCompteApporteur() {
		return this.compteApporteur;
	}

	public void setCompteApporteur(CompteApporteur compteApporteur) {
		this.compteApporteur = compteApporteur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_REGLEMENT_APP", length = 10)
	public Date getDateReglementApp() {
		return this.dateReglementApp;
	}

	public void setDateReglementApp(Date dateReglementApp) {
		this.dateReglementApp = dateReglementApp;
	}

	@Column(name = "MONTANT_REGLEMENT_APP")
	public BigDecimal getMontantReglementApp() {
		return this.montantReglementApp;
	}

	public void setMontantReglementApp(BigDecimal montantReglementApp) {
		this.montantReglementApp = montantReglementApp;
	}

	@Column(name = "TYPE_REGLEMENT", length = 60)
	public String getTypeReglement() {
		return this.typeReglement;
	}

	public void setTypeReglement(String typeReglement) {
		this.typeReglement = typeReglement;
	}

}
