package com.j3a.assurance.model;

// Generated 5 mai 2015 11:21:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SousCatVehicule generated by hbm2java
 */
@Entity
@Table(name = "sous_cat_vehicule", catalog = "zeusbd")
public class SousCatVehicule implements java.io.Serializable {

	private String codeSousCatVehicule;
	private Categorie categorie;
	private String libelleSousCatVehicule;
	private String tarif;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

	public SousCatVehicule() {
	}

	public SousCatVehicule(String codeSousCatVehicule) {
		this.codeSousCatVehicule = codeSousCatVehicule;
	}

	public SousCatVehicule(String codeSousCatVehicule, Categorie categorie,
			String libelleSousCatVehicule, String tarif, Set<Vehicule> vehicules) {
		this.codeSousCatVehicule = codeSousCatVehicule;
		this.categorie = categorie;
		this.libelleSousCatVehicule = libelleSousCatVehicule;
		this.tarif = tarif;
		this.vehicules = vehicules;
	}

	@Id
	@Column(name = "CODE_SOUS_CAT_VEHICULE", unique = true, nullable = false, length = 15)
	public String getCodeSousCatVehicule() {
		return this.codeSousCatVehicule;
	}

	public void setCodeSousCatVehicule(String codeSousCatVehicule) {
		this.codeSousCatVehicule = codeSousCatVehicule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_CATEGORIE")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "LIBELLE_SOUS_CAT_VEHICULE", length = 40)
	public String getLibelleSousCatVehicule() {
		return this.libelleSousCatVehicule;
	}

	public void setLibelleSousCatVehicule(String libelleSousCatVehicule) {
		this.libelleSousCatVehicule = libelleSousCatVehicule;
	}

	@Column(name = "TARIF", length = 10)
	public String getTarif() {
		return this.tarif;
	}

	public void setTarif(String tarif) {
		this.tarif = tarif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sousCatVehicule")
	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

}
